# set the theme
theme: unidata-jekyll-theme

# this property is useful for conditional filtering of content that is separate from the PDF.
output: web

# this will appear in an HTML meta tag, sidebar, and perhaps elsewhere
docset_version: major.minor

# this appears on the top navigation bar next to the home button
topnav_title: Topnav Title

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Site Title

# this appears in the footer
site_topic: Site Topic

# this appears in the footer
company_name: Unidata

# project logo (32x32), name, main landing page  (currently used in the footer)
project_logo: https://docs.unidata.ucar.edu/images/logos/uniLogo.png
project_name: Unidata Jekyll Theme
project_landing_page: https://unidata.ucar.edu/

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
#github_editme_path: Unidata/unidata-jekyll-theme/blob/main/

# if you have google-analytics ID, put it in. if not, edit this value to blank.
# e.g. google_analytics: UA-92978945-1
google_analytics:

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - build/
  - gradle/
  - utils/
  - .idea/
  - .gradle/
  - .git/
  - .vscode/
  - "*.gradle"
  - "gradlew*"
  - "*.gem"
  - "*.gemspec"
  - "Gemfile.*"
  - README.md
  - .gitignore

# used as a contact email and subject line for the Feedback link in the top navigation bar
feedback_subject_line: Documentation Feedback
feedback_email: plaza@unidata.ucar.edu


# if you uncomment the next line, the Feedback link gets removed
# feedback_disable: true

# if you uncomment the next line, it changes the Feedback text
# feedback_text: "Need help?"

# if you uncomment the next line, it changes where the feedback link points to
# feedback_link: "http://helpy.io/"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav

sidebars:
- home_sidebar
- mydoc_sidebar
- product1_sidebar
- product2_sidebar
- other
- unidata_sidebar

# the description is used in the feed.xml file
description: "Intended as a documentation theme based on Jekyll for use by Unidata projects."

# needed for sitemap.xml file only
# base_docs_url: https://docs.unidata.ucar.edu/netcdf-java/

#github: [metadata]
