on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the default unidata-jekyll-theme site
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install jekyll
        run: |
          gem install bundler
          bundle install
      - name: Build the default site
        run: |
          bundle exec jekyll clean
          bundle exec jekyll build
      - if: ${{ success() && github.event_name == 'pull_request' }}
        name: Upload a preview of the rendered html
        uses: actions/upload-artifact@v2
        with:
          name: default_site_preview_${{ github.sha }}
          path: _site
      - if: ${{ success() && github.event_name == 'push' }}
        name: Publish Documentation to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
